// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm3l7lmnHUny3le_RHn-tzEZGu-M83daM',
    appId: '1:932161771553:web:d37498b8ddc5ce191cab60',
    messagingSenderId: '932161771553',
    projectId: 'cursor-sample',
    authDomain: 'cursor-sample.firebaseapp.com',
    storageBucket: 'cursor-sample.firebasestorage.app',
    measurementId: 'G-6732JE25GC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIJoik9QmzSi8U2pSrQy1o-SNn0u2xYD0',
    appId: '1:932161771553:android:7d958f4fdc5ab1901cab60',
    messagingSenderId: '932161771553',
    projectId: 'cursor-sample',
    storageBucket: 'cursor-sample.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2LsmZQS9NYjW0QApww7n84he_8OQwf88',
    appId: '1:932161771553:ios:e8910c657836736f1cab60',
    messagingSenderId: '932161771553',
    projectId: 'cursor-sample',
    storageBucket: 'cursor-sample.firebasestorage.app',
    iosBundleId: 'com.example.cursorSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2LsmZQS9NYjW0QApww7n84he_8OQwf88',
    appId: '1:932161771553:ios:e8910c657836736f1cab60',
    messagingSenderId: '932161771553',
    projectId: 'cursor-sample',
    storageBucket: 'cursor-sample.firebasestorage.app',
    iosBundleId: 'com.example.cursorSample',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm3l7lmnHUny3le_RHn-tzEZGu-M83daM',
    appId: '1:932161771553:web:4a3c39ae25d06a501cab60',
    messagingSenderId: '932161771553',
    projectId: 'cursor-sample',
    authDomain: 'cursor-sample.firebaseapp.com',
    storageBucket: 'cursor-sample.firebasestorage.app',
    measurementId: 'G-PJJBL2G7L3',
  );
}
